### ISSUE TITLE
Error downloading single game

### ISSUE THREAD

**Issue by Colinifer** [pppontusw/dl-nhltv#36]
I've tried running via Docker, and standalone in Terminal. Here's the command I ran:

`docker run -v -it pontusw/nhltv:latest nhltv --team CHI -u *username* -p *password* -d games -q 900 -b 148`

I'm running on Mac OS 10.13 and Python 3.7.

The download will work all the way until 99.9%, and then I get this error:

```
Traceback (most recent call last):
  File "$/anaconda3/bin/nhltv", line 10, in <module>
    sys.exit(main())
  File "$/anaconda3/lib/python3.7/site-packages/nhltv_lib/main.py", line 63, in main
    run_loop()
  File "$/anaconda3/lib/python3.7/site-packages/nhltv_lib/main.py", line 68, in run_loop
    loop()
  File "$/anaconda3/lib/python3.7/site-packages/nhltv_lib/main.py", line 72, in loop
    get_and_download_games()
  File "$/anaconda3/lib/python3.7/site-packages/nhltv_lib/main.py", line 95, in get_and_download_games
    download(i)
  File "$/anaconda3/lib/python3.7/site-packages/nhltv_lib/main.py", line 103, in download
    dl: Download = download_game(stream)
  File "$/anaconda3/lib/python3.7/site-packages/nhltv_lib/download.py", line 72, in download_game
    _download_individual_video_files(download, len(decode_hashes))
  File "$/anaconda3/lib/python3.7/site-packages/nhltv_lib/download.py", line 435, in _download_individual_video_files
    raise DownloadError(stdout)
nhltv_lib.exceptions.DownloadError: []
```

Any ideas? Appreciate the work you've put into keeping this project up!

**Comment by pppontusw** [comment]
I’m guessing this is the TBL-CHI game from last night? I run into the same issue with that game, seems the download of one single key fails;

```
2021-01-14 18:41:37.703188 [ERROR] [AbstractCommand.cc:351] CUID#1443 - Download aborted. URI=https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/
  -> [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: Error in the pull function.
2021-01-14 18:41:37.703599 [NOTICE] [RequestGroupMan.cc:427] Download GID#020fec95a64f0b45 not complete: /mnt/external/nhl/2020020002/keys/24
``` 

Not sure how much I can do about that, if it keeps repeating there might be some issue with the file itself perhaps? 

What I usually do if this happens is download another stream- for example, if you select TBL as the team instead you automatically get the TBL feed and that one works for me. Not the best solution since it means the commentators usually are biased against your team.. but it at least let’s you watch the game :)

I’ll keep the issue open for now, as I might look into if I could switch the download provider when it fails repeatedly, but I’m not sure when I might have time to do so

**Comment by Colinifer** [comment]
It's not working for any game. I can pick any team, or game, and at 99.9% it crashes.

**Comment by pppontusw** [comment]
Ok, so downloading the TBL game that I verified doesn’t work either? If you run the program standalone there should be a log called something like 2020002002_fail_*.log, can you share that file? Interested to see if it’s the exact same error

**Comment by Colinifer** [comment]
Here you go. Here's the command I ran for the download:

`nhltv --team TBL -u *username* -p *password*  -q 1500 -b 3 -d games/`

[2020020002_fail_2021-01-15T18:11:23.952772.log](https://github.com/pppontusw/dl-nhltv/files/5823412/2020020002_fail_2021-01-15T18.11.23.952772.log)

**Comment by pppontusw** [comment]
Thanks! 

Just verified that the same command does work for me, so I guess this is harder to pin down than I thought. 
I can see from the timestamps that the downloads take significantly longer in your case than it does for me (probably related to internet speed) so it might just be for example more likely that one of these connection errors pop up - since you mentioned it happens for you on all games, and I would estimate it happens for me roughly 1 out of 100 games

The actual error happens in aria2 (which I depend on to do the actual downloading of files), probably more specifically in whichever library they use to handle TLS. 
Annoyingly, I can't find anything to indicate that anyone else has run into specifically these errors, from my google searches everyone else seems to have more or less expected errors - but I don't find anything matching "aria2 SSL/TLS handshake failure: Connection aborted" or the one I got earlier which was "aria2 SSL/TLS handshake failure: Error in the pull function.".

I was wondering why the retry functionality hasn't worked here (as aria2 is configured to retry indefinitely), but from reading the documentation I believe the retry functionality only kicks in if there's an actual failure response from the server, which isn't happening here as the connection is failing in the handshake process (so we never get a HTTP response from the server). 

Only solution I can think of here would be to build custom retry functionality, something like scanning the error file and building a list of failed URLs to retry one-by-one until they succeed, which I believe they would likely eventually do. 
My guess is that it's simply a small connection interruption or something like that which causes the failures, and if it was retried it'd most likely succeed. 
This isn't a very small thing to build though - it's something I'd like to do, as these errors are very annoying especially if they are frequent - but I'm not sure when I might have time to do so

**Comment by pppontusw** [comment]
Hmm I actually had an idea for a quick and dirty possible fix, but I can't really verify it as this very rarely affects me - though maybe you can help me test it @Colinifer ? 

I pushed it to docker as a new version, but I'd prefer to wait to see that it actually works before overwriting the previous version, so you could run it using the 2.2.3 tag as in: `docker run -v -it pontusw/nhltv:2.2.3 nhltv --team ...` and report back whether or not that version solves your problem? If any errors are detected it should print how many and attempt to retry the download up to 5 times

**Comment by Colinifer** [comment]
Giving it a go now. The slow download might be a result of my hardware (Mac 2011 running MacOs 10.13) and it runs faster on my laptop.

Where do files save when running it via Docker as opposed to running it manually?

**Comment by pppontusw** [comment]
It depends what you enter as the `-v` parameter in Docker, that controls what volume is mounted in the container, for example the example from the readme (also copied it below) would save it into `/your/media/folder` - so essentially replace the part before the colon with whatever local path you want to save to. I think you can also use a relative path if you prefix with ./ like `-v ./folder-in-your-current-directory:/home/nhltv/media`. /home/nhltv is the path where the script runs inside the docker container, so if you change the `-d` parameter, you also need to change it accordingly in the `-v` parameter to match

readme example;
 `docker run -v /your/media/folder/:/home/nhltv/media -it pontusw/nhltv:latest nhltv --team NSH -u *username* -p *password* -d media`

**Comment by Colinifer** [comment]
Looks like NHL blacklisted me for a bit since I tried this too many times. Appreciate the pointers and your time. I'll give this another shot later today and let you know if it works.

**Comment by pppontusw** [comment]
> Looks like NHL blacklisted me for a bit since I tried this too many times. Appreciate the pointers and your time. I'll give this another shot later today and let you know if it works.

Yeah, that happens sometimes, they don't like too many downloads in a short time 😬  usually resolves in an hour or two though. And no worries, it'd be great to get to the bottom of this issue, as mentioned I had seen it before on occasion but this is a great excuse to try to fix it once and for all since it seems to be reproducible for you. It's always particularly tricky to try to solve an issue when you can't yourself actually test it 😄

**Comment by Colinifer** [comment]
Looks like your fix worked! I'm able to download 2021-01-16_CHI-TBL for the game from 01-15.


Only issue now is Docker doesn't save the files in the directory I designated with `-v`. Running the command manually with `nhltv --team CHI -u *username* -p *password* -q 1500 -b 6 -d games/` works and it adds it to the correct folder – in this case it's `games/`.

I tried the following with the Docker command:
`docker run -v ~/Documents/dev/GitHub/Cloned/pppontusw-dl-nhltv:/home/nhltv/media -it pontusw/nhltv:2.2.3 nhltv -u *username* -p *password* -t CHI -b 6 -d games/ --short-debug`

I was running with `--short-debug` to give multiple attempts in a short period of time but it works running manually in the command line.

I assume this is user error?

**Comment by pppontusw** [comment]
Great to hear the fix seems to work 👍  

It looks like there’s a mismatch between the mounted folder /home/nhltv/*media* but you passed -d games/ so you need to either mount /home/nhltv/games, or change the download directory to -d media 

As it is now it will download the videos into a directory that isn’t mounted, so that’s why you don’t see it as it’s only visible inside the docker container

**Comment by Colinifer** [comment]
Awesome – I believe I figured it out. Thanks for all of your time and help!

Best of luck to your team this season too 😀
