### ISSUE TITLE
Can't download game because not yet archived

### ISSUE THREAD

**Issue by linosome** [pppontusw/dl-nhltv#38]
When trying to download a game, I get the following message:

Oct 13 15:30:31 - Logging in to NHL.com..  
Oct 13 15:30:32 - Looking up games..  
Oct 13 15:30:34 - Stream was found for game 2022020007 that is not archived yet, waiting..  
Oct 13 15:30:34 - No games to download, waiting 10 minutes before checking again..  

This happens for any game that I'm trying to download. On the nhl tv page they are available. 
In nhltv_lib/stream.py we are checking if the desired stream has the appropriate state to be downloaded ("MEDIA_ARCHIVE"). This isn't the case. The games (even though they're done) have state "MEDIA_OFF". Just trying to download them nevertheless doesn't work.

Thanks for looking into this.

**Comment by pppontusw** [comment]
Hey @linosome , sorry for the super late response - I’ve had a couple years off from watching hockey due to life circumstances 😅  the NHL API had gone through some major changes during that time which is probably why it stopped working - anyway, if you are still interested in this I’ve just reworked the script to work with the new NHL API (which has an explicit “isDelivered” status) so hopefully this should all work now
